# Brug et officielt Java image
FROM openjdk:17-alpine

# Opret en mappe i containeren
WORKDIR /app

# Kopier alle filer fra din computer til containeren
COPY . .

# Byg Java serveren
RUN javac Server.java

# Start serveren
CMD ["java", "Server"]
